PROGRAMS= video_control 
MODULES= glib-2.0 gstreamer-video-1.0
CFLAGS= -g -Wall -Wextra `pkg-config --cflags $(MODULES)`
LDFLAGS= `pkg-config --libs $(MODULES)`
all: $(PROGRAMS)
clean:
	-rm -f $(PROGRAMS)
.PHONY: all clean
