MODULES= gstreamer-1.0 gstreamer-base-1.0 gstreamer-video-1.0
CFLAGS= -Wall -g -O0 -fPIC `pkg-config --cflags $(MODULES)`
LDFLAGS= `pkg-config --libs $(MODULES)` -shared
PLUGINS= myfilter.so myvideofilter.so

all: $(PLUGINS)
clean:
	rm -f myfilter.so
.PHONY: all clean

myfilter.so: myfilter2.c
	cc $(CFLAGS) $(LDFLAGS) myfilter2.c -o $@

myvideofilter.so: myvideofilter2.c
	cc $(CFLAGS) $(LDFLAGS) myvideofilter2.c -o $@
