TARGETS= hello
MODULES= glib-2.0 gstreamer-1.0
CFLAGS= -g -Wall -Wextra `pkg-config --cflags $(MODULES)`
LDFLAGS= `pkg-config --libs $(MODULES)`
all: $(TARGETS)
clean:
	-rm -f $(TARGETS)
.PHONY: all clean
