MODULES= gstreamer-1.0 gstreamer-base-1.0 gstreamer-video-1.0
CFLAGS= -Wall -g -O0 -fPIC `pkg-config --cflags $(MODULES)`
LDFLAGS= `pkg-config --libs $(MODULES)` -shared
PLUGINS= myfilter.so myvideofilter.so

all: $(PLUGINS)
clean:
	rm -f myfilter.so
	rm -f myvideofilter.so
.PHONY: all clean

myfilter.so: myfilter2.c
	cc $(CFLAGS) myfilter2.c -o $@ $(LDFLAGS)

myvideofilter.so: myvideofilter2.c
	cc $(CFLAGS) myvideofilter2.c -o $@ $(LDFLAGS)
